#!/usr/bin/env bash
# Install the dashboard agent NATIVELY on the host (not in a container) so the
# web terminal and `link` flow run directly on the actual server. Idempotent —
# safe to re-run to upgrade.
#
# Two ways to run this:
#
#   # A) One-liner over the internet (no clone needed):
#   curl -fsSL https://raw.githubusercontent.com/kyesworld26/dashboard/main/install-host.sh | sudo bash
#
#   # B) From a local clone of the repo:
#   git clone https://github.com/kyesworld26/dashboard.git
#   sudo bash dashboard/install-host.sh
#
# Override the hub or paths via env:
#   sudo HUB_URL=wss://my.hub/agent SERVER_ROOT=/opt/myapp bash install-host.sh
#
# After install:
#   sudo systemctl status dashboard-agent
#   sudo journalctl -u dashboard-agent -f
#   dashboard-link                                  # link to a dashboard account

set -euo pipefail

REPO_URL=${REPO_URL:-https://github.com/kyesworld26/dashboard.git}
REPO_REF=${REPO_REF:-main}

INSTALL_DIR=/opt/dashboard-agent
DATA_DIR=/var/lib/dashboard-agent
SERVICE_USER=root                                    # root so the terminal is a real host shell
HUB_URL=${HUB_URL:-wss://dashboard.kyesworld.com/agent}
SERVER_ROOT=${SERVER_ROOT:-/home/server}

if [[ $EUID -ne 0 ]]; then
  echo "error: this installer must run as root (sudo)." >&2
  exit 1
fi

# Locate the source tree containing tunnel.js etc. When invoked via
# `curl | sudo bash`, this script is piped from stdin (BASH_SOURCE is empty or
# /dev/stdin), so we fall back to cloning the repo into a temp dir.
SRC_FILES=(tunnel.js server.js link.js token.js package.json)
SCRIPT_DIR=""
if [[ -n "${BASH_SOURCE[0]:-}" && -f "${BASH_SOURCE[0]}" ]]; then
  candidate=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
  have_all=1
  for f in "${SRC_FILES[@]}"; do [[ -f "$candidate/$f" ]] || { have_all=0; break; }; done
  [[ $have_all -eq 1 ]] && SCRIPT_DIR="$candidate"
fi
if [[ -z "$SCRIPT_DIR" ]]; then
  echo "==> Fetching agent sources from $REPO_URL ($REPO_REF)..."
  command -v git >/dev/null 2>&1 || {
    if command -v apt-get >/dev/null 2>&1; then apt-get install -y git
    elif command -v dnf >/dev/null 2>&1; then dnf install -y git
    else echo "install git first" >&2; exit 1; fi
  }
  TMP_SRC=$(mktemp -d)
  git clone --depth 1 --branch "$REPO_REF" "$REPO_URL" "$TMP_SRC"
  SCRIPT_DIR="$TMP_SRC"
fi

echo "==> Checking Node.js (need >= 20)..."
need_node=0
if ! command -v node >/dev/null 2>&1; then
  need_node=1
else
  major=$(node -p "process.versions.node.split('.')[0]")
  [[ "$major" -lt 20 ]] && need_node=1
fi
if [[ $need_node -eq 1 ]]; then
  if command -v apt-get >/dev/null 2>&1; then
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt-get install -y nodejs
  elif command -v dnf >/dev/null 2>&1; then
    curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
    dnf install -y nodejs
  else
    echo "error: install Node.js 20+ manually, then re-run." >&2
    exit 1
  fi
fi
echo "    Node: $(node --version)"

echo "==> Installing agent files to $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR"
for f in tunnel.js server.js link.js token.js package.json; do
  cp "$SCRIPT_DIR/$f" "$INSTALL_DIR/$f"
done
[[ -f "$SCRIPT_DIR/package-lock.json" ]] && cp "$SCRIPT_DIR/package-lock.json" "$INSTALL_DIR/" || true

echo "==> Installing npm dependencies..."
cd "$INSTALL_DIR"
npm install --omit=dev --no-audit --no-fund

echo "==> Preparing data directory at $DATA_DIR..."
mkdir -p "$DATA_DIR"
chmod 700 "$DATA_DIR"

# Best-effort: make sure docker / docker-compose are present so the agent can
# manage the host's container stack. Don't fail the installer if they aren't.
if ! command -v docker >/dev/null 2>&1; then
  echo "    note: 'docker' isn't on PATH — install it if you want the agent to manage docker services."
fi

echo "==> Writing systemd unit /etc/systemd/system/dashboard-agent.service..."
cat >/etc/systemd/system/dashboard-agent.service <<EOF
[Unit]
Description=Dashboard agent (outbound tunnel to hub + local management API)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
WorkingDirectory=$INSTALL_DIR
Environment=HUB_URL=$HUB_URL
Environment=AGENT_DATA_DIR=$DATA_DIR
Environment=SERVER_ROOT=$SERVER_ROOT
ExecStart=$(command -v node) $INSTALL_DIR/tunnel.js
Restart=always
RestartSec=5
# Generous limits — this process spawns shells for the web terminal.
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF

echo "==> Installing 'dashboard-link' wrapper to /usr/local/bin..."
cat >/usr/local/bin/dashboard-link <<EOF
#!/usr/bin/env bash
# Auto-generated by services/agent/install-host.sh — runs link.js with the
# same env the systemd unit uses so tokens land where tunnel.js is watching.
exec sudo HUB_URL="$HUB_URL" AGENT_DATA_DIR="$DATA_DIR" $(command -v node) $INSTALL_DIR/link.js "\$@"
EOF
chmod +x /usr/local/bin/dashboard-link

echo "==> Enabling and starting dashboard-agent..."
systemctl daemon-reload
systemctl enable dashboard-agent >/dev/null
systemctl restart dashboard-agent

sleep 2
echo ""
systemctl --no-pager --lines=10 status dashboard-agent || true

echo ""
echo "============================================================"
echo "Installed."
echo ""
echo "  Link this server to a dashboard account (can be re-run to ADD links):"
echo "    dashboard-link"
echo ""
echo "  Live logs:"
echo "    sudo journalctl -u dashboard-agent -f"
echo ""
echo "  Config (edit then 'systemctl restart dashboard-agent'):"
echo "    /etc/systemd/system/dashboard-agent.service"
echo "============================================================"
